theme: jekyll-theme-cayman
permalink: /blog/:year/:month/:day/:title
include:
  - _data

# Outputting
#permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/